# This is a generated file based on the test code in 'inst/tinytest/test_setops__.R' to run the tests in a clean subprocess with package(s) nanotime then bit64 attached.
# It is generated by 'tools/createTestSetopsCases.R' and should not be edited directly.
library( nanotime )
library( bit64 )
makeNanos <- 
function () 
{
    nt1 <- nanotime(c("2026-01-01T00:00:00Z", "2026-01-02T00:00:00Z", 
        "2026-01-03T00:00:00Z"))
    nt2 <- nanotime(c("2026-01-02T00:00:00Z", "2026-01-03T00:00:00Z", 
        "2026-01-04T00:00:00Z"))
    ni1 <- as.nanoival("+2026-01-01 12:12:14 -> 2026-01-03 12:12:19+")
    list(nt1 = nt1, nt2 = nt2, ni1 = ni1)
}
runSetopsTests <- 
function (tag = NULL) 
{
    options(nanotimeFormat = "%Y-%m-%d %H:%M:%S")
    n <- makeNanos()
    nt1 <- n$nt1
    nt2 <- n$nt2
    ni1 <- n$ni1
    expect_identical(union(nt1, nt2), nanotime(c("2026-01-01T00:00:00Z", 
        "2026-01-02T00:00:00Z", "2026-01-03T00:00:00Z", "2026-01-04T00:00:00Z")), 
        info = paste(tag, "union(nanotime, nanotime)"))
    expect_identical(union(1L, ni1), c(1 + (0+0i), as.complex(ni1)), 
        info = paste(tag, "union(integer, nanoival)"))
    expect_identical(union(1L, nt1), bit64::as.integer64(c("1", 
        "1767225600000000000", "1767312000000000000", "1767398400000000000")), 
        info = paste(tag, "union(integer, nanotime)"))
    expect_identical(union(nt1, 1L), bit64::as.integer64(c("1767225600000000000", 
        "1767312000000000000", "1767398400000000000", "1")), 
        info = paste(tag, "union(nanotime, integer)"))
    expect_identical(union(1L, 1), 1, info = paste(tag, "union(integer, double)"))
    if ("bit64" %in% search()) {
        expect_identical(union(as.integer64("1767312000000000000"), 
            nt1), as.integer64(nt1), info = paste(tag, "union(integer64, nanotime)"))
        expect_identical(union(1L, as.integer64(1L)), as.integer64(1L), 
            info = paste(tag, "union(integer, integer64)"))
        expect_identical(union(as.integer64(1L), 1L), as.integer64(1L), 
            info = paste(tag, "union(integer64, integer)"))
    }
    expect_identical(intersect(nt1, nt2), nanotime(c("2026-01-02T00:00:00Z", 
        "2026-01-03T00:00:00Z")), info = paste(tag, "intersect(nanotime, nanotime)"))
    expect_identical(intersect(nt1, ni1), nanotime(c("2026-01-02T00:00:00Z", 
        "2026-01-03T00:00:00Z")), info = paste(tag, "intersect(nanotime, nanoival)"))
    expect_identical(intersect(1L, ni1), complex(), info = paste(tag, 
        "intersect(integer, nanoival)"))
    expect_identical(intersect(1L, nt1), bit64::integer64(), 
        info = paste(tag, "intersect(integer, nanotime)"))
    expect_identical(intersect(nt1, 1L), bit64::integer64(), 
        info = paste(tag, "intersect(nanotime, integer)"))
    expect_identical(intersect(1L, 1), 1, info = paste(tag, "intersect(integer, double)"))
    if ("bit64" %in% search()) {
        expect_identical(intersect(as.integer64("1767312000000000000"), 
            nt1), as.integer64("1767312000000000000"), info = paste(tag, 
            "intersect(integer64, nanotime)"))
        expect_identical(intersect(1L, as.integer64(1L)), as.integer64(1L), 
            info = paste(tag, "intersect(integer, integer64)"))
        expect_identical(intersect(as.integer64(1L), 1L), as.integer64(1L), 
            info = paste(tag, "intersect(integer64, integer)"))
    }
    expect_identical(setdiff(nt1, nt2), nanotime("2026-01-01T00:00:00Z"), 
        info = paste(tag, "setdiff(nanotime, nanotime)"))
    expect_identical(setdiff(nt1, ni1), nanotime("2026-01-01T00:00:00Z"), 
        info = paste(tag, "setdiff(nanotime, nanoival)"))
    expect_identical(setdiff(1L, ni1), 1L, info = paste(tag, 
        "setdiff(integer, nanoival)"))
    expect_identical(setdiff(ni1, 1L), as.complex(ni1), info = paste(tag, 
        "setdiff(nanoival, integer)"))
    expect_identical(setdiff(1L, nt1), 1L, info = paste(tag, 
        "setdiff(integer, nanotime)"))
    expect_identical(setdiff(nt1, 1L), bit64::as.integer64(nt1), 
        info = paste(tag, "setdiff(nanotime, integer)"))
    expect_identical(setdiff(1L, 1), integer(), info = paste(tag, 
        "setdiff(integer, double)"))
    if ("bit64" %in% search()) {
        expect_identical(setdiff(as.integer64("1767312000000000000"), 
            nt1), as.integer64("1767312000000000000"), info = paste(tag, 
            "setdiff(integer64, nanotime)"))
        expect_identical(setdiff(1L, as.integer64(1L)), 1L, info = paste(tag, 
            "setdiff(integer, integer64)"))
        expect_identical(setdiff(as.integer64(1L), 1L), as.integer64(1L), 
            info = paste(tag, "setdiff(integer64, integer)"))
    }
    expect_identical(setequal(nt1, nt2), FALSE, info = paste(tag, 
        "setequal(nanotime, nanotime)"))
    expect_identical(setequal(nt1, ni1), FALSE, info = paste(tag, 
        "setequal(nanotime, nanoival)"))
    expect_identical(setequal(1L, ni1), FALSE, info = paste(tag, 
        "setequal(integer, nanoival)"))
    expect_identical(setequal(1L, nt1), FALSE, info = paste(tag, 
        "setequal(integer, nanotime)"))
    expect_identical(setequal(nt1, 1L), FALSE, info = paste(tag, 
        "setequal(nanotime, integer)"))
    expect_identical(setequal(1L, 1), TRUE, info = paste(tag, 
        "setequal(integer, double)"))
    if ("bit64" %in% search()) {
        expect_identical(setequal(as.integer64("1767312000000000000"), 
            nt1), FALSE, info = paste(tag, "setequal(integer64, nanotime)"))
        expect_identical(setequal(1L, as.integer64(1L)), TRUE, 
            info = paste(tag, "setequal(integer, integer64)"))
        expect_identical(setequal(as.integer64(1L), 1L), TRUE, 
            info = paste(tag, "setequal(integer64, integer)"))
    }
    expect_identical(is.element(nt1, nt2), c(FALSE, TRUE, TRUE), 
        info = paste(tag, "is.element(nanotime, nanotime)"))
    expect_identical(is.element(nt1, ni1), c(FALSE, FALSE, FALSE), 
        info = paste(tag, "is.element(nanotime, nanoival)"))
    expect_identical(is.element(1L, ni1), FALSE, info = paste(tag, 
        "is.element(integer, nanoival)"))
    expect_identical(is.element(1L, nt1), FALSE, info = paste(tag, 
        "is.element(integer, nanotime)"))
    expect_identical(is.element(nt1, 1L), c(FALSE, FALSE, FALSE), 
        info = paste(tag, "is.element(nanotime, integer)"))
    expect_identical(is.element(1L, 1), TRUE, info = paste(tag, 
        "is.element(integer, double)"))
    if ("bit64" %in% search()) {
        expect_identical(is.element(as.integer64("1767312000000000000"), 
            nt1), TRUE, info = paste(tag, "is.element(integer64, nanotime)"))
        expect_identical(is.element(1L, as.integer64(1L)), TRUE, 
            info = paste(tag, "is.element(integer, integer64)"))
        expect_identical(is.element(as.integer64(1L), 1L), TRUE, 
            info = paste(tag, "is.element(integer64, integer)"))
    }
    invisible()
}
runSetopsTests("(c) nanotime then bit64:")
