baseFilePath <- file.path("inst", "tinytest")
baseFileName <- "test_setops__.R"
sourceFile <- file.path(baseFilePath, baseFileName)
source(sourceFile)

for (testCase in seq_along(testFilesToCreateWithGivenPackageAttachOrder)) {
  testName <- names(testFilesToCreateWithGivenPackageAttachOrder)[testCase]
  testFile <- file.path(baseFilePath, sub("(.*)([.]R)$", paste0("\\1", paste0(testFilesToCreateWithGivenPackageAttachOrder[[testCase]], collapse = "_"), "\\2"), baseFileName))
    writeLines(c(
        paste0("# This is a generated file based on the test code in ", sQuote(sourceFile), " to run the tests in a clean subprocess with package(s) ", paste(testFilesToCreateWithGivenPackageAttachOrder[[testCase]], collapse = " then "), " attached."),
        "# It is generated by 'tools/createTestSetopsCases.R' and should not be edited directly.",
        paste("library(", testFilesToCreateWithGivenPackageAttachOrder[[testCase]], ")", collapse = "\n"),
        "makeNanos <- ", deparse(makeNanos),
        "runSetopsTests <- ", deparse(runSetopsTests),
        paste0("runSetopsTests(\"", testName, ":\")")
    ), con = testFile)
}
