# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nanoival_intersect_idx_time_interval_impl <- function(nv1, nv2) {
    .Call(`_nanotime_nanoival_intersect_idx_time_interval_impl`, nv1, nv2)
}

nanoival_intersect_time_interval_impl <- function(nv1, nv2) {
    .Call(`_nanotime_nanoival_intersect_time_interval_impl`, nv1, nv2)
}

nanoival_setdiff_time_interval_impl <- function(nv1, nv2) {
    .Call(`_nanotime_nanoival_setdiff_time_interval_impl`, nv1, nv2)
}

nanoival_union_impl <- function(nv1, nv2) {
    .Call(`_nanotime_nanoival_union_impl`, nv1, nv2)
}

nanoival_intersect_impl <- function(nv1, nv2) {
    .Call(`_nanotime_nanoival_intersect_impl`, nv1, nv2)
}

nanotime_wday_impl <- function(tm_v, tz_v) {
    .Call(`_nanotime_nanotime_wday_impl`, tm_v, tz_v)
}

nanotime_mday_impl <- function(tm_v, tz_v) {
    .Call(`_nanotime_nanotime_mday_impl`, tm_v, tz_v)
}

nanotime_month_impl <- function(tm_v, tz_v) {
    .Call(`_nanotime_nanotime_month_impl`, tm_v, tz_v)
}

nanotime_year_impl <- function(tm_v, tz_v) {
    .Call(`_nanotime_nanotime_year_impl`, tm_v, tz_v)
}

nanotime_make_impl <- function(nt_v, tz_v) {
    .Call(`_nanotime_nanotime_make_impl`, nt_v, tz_v)
}

